
name: Argocd Deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  pull-requests: write
  statuses: write
  actions: read
  contents: read

jobs:
  call-Argocd-workflow:
    uses: ./.github/workflows/deploy.yaml
    with:
      work-dir: "environments/Setup-Argocd"
      aws-region: "eu-north-1"
    secrets:
      CI_ROLE: ${{ secrets.CI_ROLE }}
      # SSH_KEY_GITHUB_ACTIONS: ${{ secrets.SSH_KEY_GITHUB_ACTIONS }}

  deploy-scripts:
    needs: call-Argocd-workflow
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.CI_ROLE }}
        aws-region: eu-north-1

    - name: Set up SSH
      run: |
         eval "$(ssh-agent -s)"
         ssh-add - <<< "${{ secrets.SSH_KEY_GITHUB_ACTIONS }}"
         ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Grant execute permissions to scripts
      run: |
          chmod +x environments/Setup-Argocd/runner.sh
          chmod +x environments/Setup-Argocd/argocd.sh

    - name: Run first script
      run: |
          environments/Setup-Argocd/runner.sh
          echo "Running the first script!"

    - name: Update kubeconfig
      run: |
          aws eks --region eu-north-1 update-kubeconfig --name hr-dev-eks-cloud

    - name: Verify access
      run: kubectl get nodes

    - name: Run Second Script and Install ArgoCD
      run: |
          environments/Setup-Argocd/argocd.sh
          echo "Running the second script!"
         
###